spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/girl?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.zhouc.dto
  mapper-locations: classpath:mapper/*.xml

