girl:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/girl?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456

boy:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boy?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456


